CREATE TABLE IF NOT EXISTS users (
  id INT UPRIMARY KEY,
  did VARCHAR(255) NOT NULL,
  handle VARCHAR(255) NOT NULL,
  active BOOLEAN DEFAULT NULL,
  nickname VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS status (
  id INT PRIMARY KEY,
  uri VARCHAR(255) NOT NULL,
  author_did VARCHAR NOT NULL REFERENCES users.did,
  content VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  indexed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS session (
  id VARCHAR(255) PRIMARY KEY,
  user_did VARCHAR NOT NULL,
  expires_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AtProtoSession (
  key VARCHAR PRIMARY KEY,
  session VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS AtProtoState (
  key VARCHAR PRIMARY KEY,
  state VARCHAR NOT NULL
);