CREATE TABLE IF NOT EXISTS users (
  did VARCHAR PRIMARY KEY,
  handle VARCHAR NOT NULL,
  active BOOLEAN DEFAULT null,
  nickname VARCHAR,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS status (
  uri VARCHAR PRIMARY KEY,
  author_did VARCHAR NOT NULL,
  content VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)